wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1675729077.278843
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.9
      8:
      - 1
      - 3
      - 5
data_size:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 0.0008
